services:
  backend:
    container_name: ubl-backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5061:5000"
    restart: unless-stopped
    networks:
      - ubl-network

  # cloudflared:
  #   image: cloudflare/cloudflared:latest
  #   container_name: cloudflared-tunnel
  #   command: tunnel --no-autoupdate run --token eyJhIjoiODkwMTgyNjBkOTYyODdhYzg0MDUwYTA2YTZmYTMwOWEiLCJ0IjoiYWQwZmRiZTMtNzJhYi00ZmZmLTgxOTUtMDU1ZTg1ZmYzMmUyIiwicyI6Ik5ETXlaVE00TVdVdE1XWmxOUzAwTnpRMkxUbGlPVGt0WldFM1lqaGlOell6Tm1ReCJ9
  #   restart: unless-stopped
  #   depends_on:
  #     - backend
  #   networks:
  #     - ubl-network

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared-tunnel
    command: tunnel --url http://backend:5000
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - ubl-network

networks:
  ubl-network:
    driver: bridge
